language: python

matrix:
  include:
  # Ubuntu 18.04 LTS
    - os: linux
      dist: bionic
      python: '3.7'
      env: PAGER=/bin/cat

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq pigz graphviz

install:
    - ./bootstrap.sh
    - mkdir -p example-configurations/travis-example/output_data

script:
    - cd example-configurations/travis-example/
    - ./../../uap -vvv travis_uap_config.yaml status
    - ./../../uap -vvv travis_uap_config.yaml render
    - ./../../uap -vvv travis_uap_config.yaml steps
    - ./../../uap -vvv travis_uap_config.yaml run-info
    - ./../../uap -vvv travis_uap_config.yaml volatilize
